sudo: required
lauguage: generic
services: 
  - docker

before_install:
  - docker build -t kittyspecial/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true kittyspecial/docker-react npm run test
